table _Medidas
	lineageTag: 3e53132e-386d-44e4-b568-b5a781404dcd

	measure Total_Colaboradores_Ativos =
			
			
			CALCULATE([Total_Colaboradores_Dataset], 'fact-attrition'[Attrition] = "No")
		formatString: 0
		lineageTag: 9583f2a0-20dd-4a75-9403-fe4eeae072ad

	measure Total_Colaboradores_Sairam =
			
			
			CALCULATE([Total_Colaboradores_Dataset], 'fact-attrition'[Attrition] = "Yes")
		formatString: 0
		lineageTag: 0ab4bc98-1d34-42f0-b490-794c53f83fcd

	measure '%Taxa_Atrito (Rotatividade)' = ```
			
			 -- esta medida não vai ser necessária
			DIVIDE([Total_Colaboradores_Sairam], [Total_Colaboradores_Dataset])
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: a54f844c-edbb-4c01-a746-af66494c27e3

	measure Total_Colaboradores_Dataset = ```
			
			
			DISTINCTCOUNT('fact-attrition'[EmployeeNumber]) 
			```
		formatString: 0
		lineageTag: 0957bf60-199e-436c-bf9e-e0dafd700441

	column 'Dev by'
		lineageTag: 055606ff-6bae-4fb1-912c-5adf71402d98
		summarizeBy: none
		isNameInferred
		sourceColumn: [Dev by]

		annotation SummarizationSetBy = Automatic

	column 'Last update'
		formatString: General Date
		lineageTag: 2a6f3e5f-52be-4479-887c-05b6ac74773d
		summarizeBy: none
		isNameInferred
		sourceColumn: [Last update]

		variation Variation
			isDefault
			relationship: 7c56ff5e-282f-42ac-ba05-8efb509530c0
			defaultHierarchy: LocalDateTable_e5c9f64c-d53b-414e-a7b4-58b42903296a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition _Medidas = calculated
		mode: import
		source = ```
				
				
				  ROW("Dev by", "Grupo #2 Power Squad", "Last update", TODAY())
				  
				```

	annotation PBI_Id = 5fc5796d83374d2783fd9bf08ce565ba

