table dim-job
	lineageTag: 33c6c7d5-e933-430a-a88c-c67833527f79

	column Job_Id
		dataType: int64
		formatString: 0
		lineageTag: b809a834-ad58-4d41-8edb-1c706e2d03f8
		summarizeBy: none
		sourceColumn: Job_Id

		annotation SummarizationSetBy = Automatic

	column JobLevel
		dataType: int64
		formatString: 0
		lineageTag: c3a87d25-067f-43f4-9b5f-262119bce24b
		summarizeBy: none
		sourceColumn: JobLevel

		annotation SummarizationSetBy = Automatic

	column JobRole
		dataType: string
		lineageTag: e890adac-a0ed-466b-9d2a-7e42daa53e6f
		summarizeBy: none
		sourceColumn: JobRole

		annotation SummarizationSetBy = Automatic

	partition dim-job = m
		mode: import
		queryGroup: TABELAS-DIM
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Formando\Desktop\IBM\dados\IBM-HR-Employee-Attrition.csv"),[Delimiter=";", Columns=35, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Age", Int64.Type}, {"Attrition", type text}, {"BusinessTravel", type text}, {"DailyRate", Int64.Type}, {"Department", type text}, {"DistanceFromHome", Int64.Type}, {"Education", Int64.Type}, {"EducationField", type text}, {"EmployeeCount", Int64.Type}, {"EmployeeNumber", Int64.Type}, {"EnvironmentSatisfaction", Int64.Type}, {"Gender", type text}, {"HourlyRate", Int64.Type}, {"JobInvolvement", Int64.Type}, {"JobLevel", Int64.Type}, {"JobRole", type text}, {"JobSatisfaction", Int64.Type}, {"MaritalStatus", type text}, {"MonthlyIncome", Int64.Type}, {"MonthlyRate", Int64.Type}, {"NumCompaniesWorked", Int64.Type}, {"Over18", type text}, {"OverTime", type text}, {"PercentSalaryHike", Int64.Type}, {"PerformanceRating", Int64.Type}, {"RelationshipSatisfaction", Int64.Type}, {"StandardHours", Int64.Type}, {"StockOptionLevel", Int64.Type}, {"TotalWorkingYears", Int64.Type}, {"TrainingTimesLastYear", Int64.Type}, {"WorkLifeBalance", Int64.Type}, {"YearsAtCompany", Int64.Type}, {"YearsInCurrentRole", Int64.Type}, {"YearsSinceLastPromotion", Int64.Type}, {"YearsWithCurrManager", Int64.Type}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Changed Type",{"EmployeeNumber", "Age", "Attrition", "BusinessTravel", "DailyRate", "Department", "DistanceFromHome", "Education", "EducationField", "EmployeeCount", "EnvironmentSatisfaction", "Gender", "HourlyRate", "JobInvolvement", "JobLevel", "JobRole", "JobSatisfaction", "MaritalStatus", "MonthlyIncome", "MonthlyRate", "NumCompaniesWorked", "Over18", "OverTime", "PercentSalaryHike", "PerformanceRating", "RelationshipSatisfaction", "StandardHours", "StockOptionLevel", "TotalWorkingYears", "TrainingTimesLastYear", "WorkLifeBalance", "YearsAtCompany", "YearsInCurrentRole", "YearsSinceLastPromotion", "YearsWithCurrManager"}),
				    #"Sorted Rows" = Table.Sort(#"Reordered Columns",{{"EmployeeNumber", Order.Ascending}}),
				    #"Reordered Columns1" = Table.ReorderColumns(#"Sorted Rows",{"EmployeeNumber", "Attrition", "Age", "BusinessTravel", "DailyRate", "Department", "DistanceFromHome", "Education", "EducationField", "EmployeeCount", "EnvironmentSatisfaction", "Gender", "HourlyRate", "JobInvolvement", "JobLevel", "JobRole", "JobSatisfaction", "MaritalStatus", "MonthlyIncome", "MonthlyRate", "NumCompaniesWorked", "Over18", "OverTime", "PercentSalaryHike", "PerformanceRating", "RelationshipSatisfaction", "StandardHours", "StockOptionLevel", "TotalWorkingYears", "TrainingTimesLastYear", "WorkLifeBalance", "YearsAtCompany", "YearsInCurrentRole", "YearsSinceLastPromotion", "YearsWithCurrManager"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Reordered Columns1",{"EmployeeCount", "Over18", "StandardHours"}),
				    #"Reordered Columns2" = Table.ReorderColumns(#"Removed Columns",{"EmployeeNumber", "Attrition", "Age", "Gender", "MaritalStatus", "DistanceFromHome", "StockOptionLevel", "BusinessTravel", "DailyRate", "Department", "Education", "EducationField", "EnvironmentSatisfaction", "HourlyRate", "JobInvolvement", "JobLevel", "JobRole", "JobSatisfaction", "MonthlyIncome", "MonthlyRate", "NumCompaniesWorked", "OverTime", "PercentSalaryHike", "PerformanceRating", "RelationshipSatisfaction", "TotalWorkingYears", "TrainingTimesLastYear", "WorkLifeBalance", "YearsAtCompany", "YearsInCurrentRole", "YearsSinceLastPromotion", "YearsWithCurrManager"}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Reordered Columns2",{"Age", "Gender", "MaritalStatus", "DistanceFromHome", "StockOptionLevel", "BusinessTravel", "DailyRate", "HourlyRate", "MonthlyIncome", "MonthlyRate", "NumCompaniesWorked", "OverTime", "PercentSalaryHike", "PerformanceRating", "TotalWorkingYears", "TrainingTimesLastYear", "YearsAtCompany", "YearsInCurrentRole", "YearsSinceLastPromotion", "YearsWithCurrManager"}),
				    #"Merged Queries" = Table.NestedJoin(#"Removed Columns1", {"Education", "EducationField"}, #"dim-education", {"EducationItem", "EducationField"}, "dim-education", JoinKind.LeftOuter),
				    #"Expanded dim-education" = Table.ExpandTableColumn(#"Merged Queries", "dim-education", {"Education_Id"}, {"dim-education.Education_Id"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded dim-education",{{"dim-education.Education_Id", "Education_Id"}}),
				    #"Removed Columns2" = Table.RemoveColumns(#"Renamed Columns",{"Education", "EducationField"}),
				    #"Merged Queries1" = Table.NestedJoin(#"Removed Columns2", {"Department"}, #"dim-department", {"Department"}, "dim-department", JoinKind.LeftOuter),
				    #"Expanded dim-department" = Table.ExpandTableColumn(#"Merged Queries1", "dim-department", {"Department_Id"}, {"Department_Id"}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Expanded dim-department",{"JobLevel", "JobRole"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Sorted Rows1" = Table.Sort(#"Removed Duplicates",{{"JobLevel", Order.Ascending}, {"JobRole", Order.Ascending}}),
				    #"Added Index" = Table.AddIndexColumn(#"Sorted Rows1", "Index", 1, 1, Int64.Type),
				    #"Reordered Columns3" = Table.ReorderColumns(#"Added Index",{"Index", "JobLevel", "JobRole"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Reordered Columns3",{{"Index", "Job_Id"}}),
				    #"Sorted Rows2" = Table.Sort(#"Renamed Columns1",{{"Job_Id", Order.Ascending}})
				in
				    #"Sorted Rows2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

