table dim-satisfaction
	lineageTag: 0876179f-615c-4937-9acf-8b08dada9b23

	column Satisfaction_Id
		dataType: int64
		formatString: 0
		lineageTag: 201de9c7-a526-4173-9a35-6d5a27067025
		summarizeBy: none
		sourceColumn: Satisfaction_Id

		annotation SummarizationSetBy = Automatic

	column Level
		dataType: string
		lineageTag: 5e8c599a-e453-406a-b833-2134ffddb733
		summarizeBy: none
		sourceColumn: Level

		annotation SummarizationSetBy = Automatic

	partition dim-satisfaction = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUfLJL1eK1YlWMgKyfVNTMktzwVxjINcjMz0DzDEBcsJSiyoVICKxAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Satisfaction_Id = _t, Level = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Satisfaction_Id", Int64.Type}, {"Level", type text}})
				in
				    #"Changed Type"

	changedProperty = Name

	annotation PBI_ResultType = Table

