table fact-attrition
	lineageTag: ce3fccef-6e78-4614-98ba-28137f9c8549

	column EmployeeNumber
		dataType: int64
		formatString: 0
		lineageTag: 28ba7088-55e3-43c9-abea-ea3e01c79144
		summarizeBy: none
		sourceColumn: EmployeeNumber

		annotation SummarizationSetBy = Automatic

	column Attrition
		dataType: string
		lineageTag: eea6f541-63ae-4419-b490-52e6d78fdcce
		summarizeBy: none
		sourceColumn: Attrition

		annotation SummarizationSetBy = Automatic

	column EnvironmentSatisfaction
		dataType: int64
		formatString: 0
		lineageTag: 22f68c3b-4441-419e-97a2-f52257c242b2
		summarizeBy: none
		sourceColumn: EnvironmentSatisfaction

		annotation SummarizationSetBy = Automatic

	column JobInvolvement
		dataType: int64
		formatString: 0
		lineageTag: 2e20c3c0-0a06-4c8e-8766-7c83733328b7
		summarizeBy: sum
		sourceColumn: JobInvolvement

		annotation SummarizationSetBy = Automatic

	column JobSatisfaction
		dataType: int64
		formatString: 0
		lineageTag: 04f4beff-171f-4725-bc03-66c329e47544
		summarizeBy: sum
		sourceColumn: JobSatisfaction

		annotation SummarizationSetBy = Automatic

	column RelationshipSatisfaction
		dataType: int64
		formatString: 0
		lineageTag: 301d3d2e-1337-4138-b62d-cbffbdf11b0d
		summarizeBy: sum
		sourceColumn: RelationshipSatisfaction

		annotation SummarizationSetBy = Automatic

	column WorkLifeBalance
		dataType: int64
		formatString: 0
		lineageTag: 528ba725-909e-41b1-a52d-0556cc081ef5
		summarizeBy: sum
		sourceColumn: WorkLifeBalance

		annotation SummarizationSetBy = Automatic

	column Education_Id
		dataType: int64
		formatString: 0
		lineageTag: 7e7d97e2-fd06-4cf5-ac54-7718d4602514
		summarizeBy: none
		sourceColumn: Education_Id

		annotation SummarizationSetBy = Automatic

	column Department_Id
		dataType: int64
		formatString: 0
		lineageTag: 073561d5-c52a-4de2-9fe4-74c5bd770007
		summarizeBy: none
		sourceColumn: Department_Id

		annotation SummarizationSetBy = Automatic

	column Job_Id
		dataType: int64
		formatString: 0
		lineageTag: 14833bcd-c4ec-4e64-b45c-63c63cb03a83
		summarizeBy: none
		sourceColumn: Job_Id

		annotation SummarizationSetBy = Automatic

	column SurveyDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 2984cd03-6a32-4fa0-9c9a-e3e7917b6de4
		summarizeBy: none
		sourceColumn: SurveyDate

		variation Variation
			isDefault
			relationship: 1d36a10e-676d-41f6-b956-04bafa3f7383
			defaultHierarchy: LocalDateTable_2fcc799b-a3ee-4406-bb0d-e1384b7c108b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	partition fact-attrition = m
		mode: import
		queryGroup: TABELAS-FACT
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Formando\Desktop\IBM\dados\IBM-HR-Employee-Attrition.csv"),[Delimiter=";", Columns=35, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Age", Int64.Type}, {"Attrition", type text}, {"BusinessTravel", type text}, {"DailyRate", Int64.Type}, {"Department", type text}, {"DistanceFromHome", Int64.Type}, {"Education", Int64.Type}, {"EducationField", type text}, {"EmployeeCount", Int64.Type}, {"EmployeeNumber", Int64.Type}, {"EnvironmentSatisfaction", Int64.Type}, {"Gender", type text}, {"HourlyRate", Int64.Type}, {"JobInvolvement", Int64.Type}, {"JobLevel", Int64.Type}, {"JobRole", type text}, {"JobSatisfaction", Int64.Type}, {"MaritalStatus", type text}, {"MonthlyIncome", Int64.Type}, {"MonthlyRate", Int64.Type}, {"NumCompaniesWorked", Int64.Type}, {"Over18", type text}, {"OverTime", type text}, {"PercentSalaryHike", Int64.Type}, {"PerformanceRating", Int64.Type}, {"RelationshipSatisfaction", Int64.Type}, {"StandardHours", Int64.Type}, {"StockOptionLevel", Int64.Type}, {"TotalWorkingYears", Int64.Type}, {"TrainingTimesLastYear", Int64.Type}, {"WorkLifeBalance", Int64.Type}, {"YearsAtCompany", Int64.Type}, {"YearsInCurrentRole", Int64.Type}, {"YearsSinceLastPromotion", Int64.Type}, {"YearsWithCurrManager", Int64.Type}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Changed Type",{"EmployeeNumber", "Age", "Attrition", "BusinessTravel", "DailyRate", "Department", "DistanceFromHome", "Education", "EducationField", "EmployeeCount", "EnvironmentSatisfaction", "Gender", "HourlyRate", "JobInvolvement", "JobLevel", "JobRole", "JobSatisfaction", "MaritalStatus", "MonthlyIncome", "MonthlyRate", "NumCompaniesWorked", "Over18", "OverTime", "PercentSalaryHike", "PerformanceRating", "RelationshipSatisfaction", "StandardHours", "StockOptionLevel", "TotalWorkingYears", "TrainingTimesLastYear", "WorkLifeBalance", "YearsAtCompany", "YearsInCurrentRole", "YearsSinceLastPromotion", "YearsWithCurrManager"}),
				    #"Sorted Rows" = Table.Sort(#"Reordered Columns",{{"EmployeeNumber", Order.Ascending}}),
				    #"Reordered Columns1" = Table.ReorderColumns(#"Sorted Rows",{"EmployeeNumber", "Attrition", "Age", "BusinessTravel", "DailyRate", "Department", "DistanceFromHome", "Education", "EducationField", "EmployeeCount", "EnvironmentSatisfaction", "Gender", "HourlyRate", "JobInvolvement", "JobLevel", "JobRole", "JobSatisfaction", "MaritalStatus", "MonthlyIncome", "MonthlyRate", "NumCompaniesWorked", "Over18", "OverTime", "PercentSalaryHike", "PerformanceRating", "RelationshipSatisfaction", "StandardHours", "StockOptionLevel", "TotalWorkingYears", "TrainingTimesLastYear", "WorkLifeBalance", "YearsAtCompany", "YearsInCurrentRole", "YearsSinceLastPromotion", "YearsWithCurrManager"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Reordered Columns1",{"EmployeeCount", "Over18", "StandardHours"}),
				    #"Reordered Columns2" = Table.ReorderColumns(#"Removed Columns",{"EmployeeNumber", "Attrition", "Age", "Gender", "MaritalStatus", "DistanceFromHome", "StockOptionLevel", "BusinessTravel", "DailyRate", "Department", "Education", "EducationField", "EnvironmentSatisfaction", "HourlyRate", "JobInvolvement", "JobLevel", "JobRole", "JobSatisfaction", "MonthlyIncome", "MonthlyRate", "NumCompaniesWorked", "OverTime", "PercentSalaryHike", "PerformanceRating", "RelationshipSatisfaction", "TotalWorkingYears", "TrainingTimesLastYear", "WorkLifeBalance", "YearsAtCompany", "YearsInCurrentRole", "YearsSinceLastPromotion", "YearsWithCurrManager"}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Reordered Columns2",{"Age", "Gender", "MaritalStatus", "DistanceFromHome", "StockOptionLevel", "BusinessTravel", "DailyRate", "HourlyRate", "MonthlyIncome", "MonthlyRate", "NumCompaniesWorked", "OverTime", "PercentSalaryHike", "PerformanceRating", "TotalWorkingYears", "TrainingTimesLastYear", "YearsAtCompany", "YearsInCurrentRole", "YearsSinceLastPromotion", "YearsWithCurrManager"}),
				    #"Merged Queries" = Table.NestedJoin(#"Removed Columns1", {"Education", "EducationField"}, #"dim-education", {"EducationItem", "EducationField"}, "dim-education", JoinKind.LeftOuter),
				    #"Expanded dim-education" = Table.ExpandTableColumn(#"Merged Queries", "dim-education", {"Education_Id"}, {"dim-education.Education_Id"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded dim-education",{{"dim-education.Education_Id", "Education_Id"}}),
				    #"Removed Columns2" = Table.RemoveColumns(#"Renamed Columns",{"Education", "EducationField"}),
				    #"Merged Queries1" = Table.NestedJoin(#"Removed Columns2", {"Department"}, #"dim-department", {"Department"}, "dim-department", JoinKind.LeftOuter),
				    #"Expanded dim-department" = Table.ExpandTableColumn(#"Merged Queries1", "dim-department", {"Department_Id"}, {"Department_Id"}),
				    #"Removed Columns3" = Table.RemoveColumns(#"Expanded dim-department",{"Department"}),
				    #"Merged Queries2" = Table.NestedJoin(#"Removed Columns3", {"JobLevel", "JobRole"}, #"dim-job", {"JobLevel", "JobRole"}, "dim-job", JoinKind.LeftOuter),
				    #"Expanded dim-job" = Table.ExpandTableColumn(#"Merged Queries2", "dim-job", {"Job_Id"}, {"Job_Id"}),
				    #"Removed Columns4" = Table.RemoveColumns(#"Expanded dim-job",{"JobLevel", "JobRole"}),
				    #"Reordered Columns3" = Table.ReorderColumns(#"Removed Columns4",{"EmployeeNumber", "Attrition", "Education_Id", "Department_Id", "Job_Id", "EnvironmentSatisfaction", "JobInvolvement", "JobSatisfaction", "RelationshipSatisfaction", "WorkLifeBalance"}),
				    #"Added Custom" = Table.AddColumn(#"Reordered Columns3", "SurveyDate", each #date(2026, 04, 01)),
				    #"Sorted Rows1" = Table.Sort(#"Added Custom",{{"EmployeeNumber", Order.Ascending}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Sorted Rows1",{{"SurveyDate", type date}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

